name: Build
on: push
jobs:
  build:
    name: Build
    permissions:
      id-token: write
      contents: write
      attestations: write
    uses: ./.github/workflows/pyinstaller.yml
    with:
      file: main.pyw
      name: allslain_gui
      icon: icon/ded.ico
      output: dist/allslain_gui.exe
      attest: false
      release: true
      tag_name: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}
