name: Release
on:
  release:
    types: [published]
jobs:
  build:
    name: Build and release
    permissions:
      attestations: write
      contents: write
      id-token: write
    uses: ./.github/workflows/pyinstaller.yml
    with:
      file: main.pyw
      name: allslain_gui
      icon: icon/ded.ico
      output: dist/allslain_gui.exe
      attest: true
      release: true
